config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books
  resources :users, only: [:show, :edit, :update, :index]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @bookform = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(book.id)
    else
      render :new  #アプリケーション２はredirect_toでやってる
    end
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def index
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<% @books.each do|book| %>
<p>Title</p>
<span>
    <%= link_to book.title, book_path(book.id) %>
</span>
<P>Opinion</P>
<span><%= book.body %></span>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<!-- form_with部分 showのパスがちがうかも-->
<%= form_with model: @bookform, url:'/books', local:true do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create book' %>
<% end %>

app/views/books/show.html.erb
<h1>Book detail</h1>
<p><%= @book.title %></p>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<% if @book.user == current_user %>
<%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %>
<% end %>

app/views/homes/top.html.erb
<h1>ここはTopページです。</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" media="all" href="/assets/application-16605eadccf37c23d1fa922dd614f45b9f2cf25723e2e4032f1975b02ea7d11f.css" data-turbolinks-track="reload">
    <script src="/assets/application-3ac47b8571e58aab844e8d0a988f0f55d8a16c1a75953470343f79cf1bec8528.js" data-turbolinks-track="reload"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <li><%= link_to 'Home', user_path(current_user.id) %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to "Books", books_path %></li>
    <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
    login中
    <% else %>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "sign_up", new_user_registration_path %></li>
    <li><%= link_to "login", new_user_session_path %></li>
    <% end %>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container"
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
            <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
            <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
            <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
          </ul>
        </div>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Use info</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName" %>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    <label for="inputIntroduction">Introduction</label>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<h1>Books</h1>

<div class="profile-container">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <h3 class="profile-name"><%= @user.name %></h3>



  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<% @books.each do|book| %>
<p>Title</p>
<span>
    <%= link_to book.title, book_path(book.id) %>
</span>
<P>Opinion</P>
<span><%= book.body %></span>
<% end %>